import http from 'node:http';
import { URL } from 'node:url';
import { createDatabase, one, many, run, audit, notify } from './db.js';
import { hashPassword, verifyPassword, issueToken, verifyToken } from './auth.js';
import { COMMON_SKILLS, ISSUE_TYPES } from './domain.js';

const db = createDatabase();
const PORT = Number(process.env.PORT || 3000);
const roles = (...allowed) => (user) => allowed.includes(user.role);
const now = () => new Date().toISOString();

function send(res, status, body) { res.writeHead(status, { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Authorization, Content-Type' }); res.end(JSON.stringify(body)); }
async function body(req) { let raw = ''; for await (const chunk of req) raw += chunk; if (!raw) return {}; try { return JSON.parse(raw); } catch { throw Object.assign(new Error('Body must be valid JSON'), { status: 400 }); } }
function requireUser(req) { const value = req.headers.authorization || ''; if (!value.startsWith('Bearer ')) throw Object.assign(new Error('Authentication required'), { status: 401 }); const claims = verifyToken(value.slice(7)); const user = one(db, 'SELECT id, name, email, role, site, skills, active FROM users WHERE id = ?', claims.sub); if (!user || !user.active) throw Object.assign(new Error('Account is unavailable'), { status: 401 }); return { ...user, skills: JSON.parse(user.skills) }; }
function allowed(user, predicate) { if (!predicate(user)) throw Object.assign(new Error('Insufficient permission'), { status: 403 }); }
function parseJson(value) { try { return JSON.parse(value || '[]'); } catch { return []; } }
function requestRow(row) { return row && { ...row, required_skills: parseJson(row.required_skills), preferred_skills: parseJson(row.preferred_skills), required_parts: parseJson(row.required_parts) }; }
function getRequest(id) { return requestRow(one(db, `SELECT r.*, m.code AS machine_code, m.name AS machine_name, m.site, u.name AS requester_name, t.name AS technician_name FROM service_requests r JOIN machines m ON m.id=r.machine_id JOIN users u ON u.id=r.requester_id LEFT JOIN users t ON t.id=r.assigned_to WHERE r.id=?`, id)); }
function transition(user, req, next, note) { const legal = { pending_approval:['approved','cancelled'], approved:['assigned','exception','cancelled'], assigned:['in_progress','exception','cancelled'], in_progress:['completed','exception'], exception:['assigned','cancelled'] }; if (!legal[req.status]?.includes(next)) throw Object.assign(new Error(`Cannot move ${req.status} request to ${next}`), { status: 409 }); run(db, "UPDATE service_requests SET status=?, updated_at=?, completed_at=CASE WHEN ?='completed' THEN ? ELSE completed_at END WHERE id=?", next, now(), next, now(), req.id); if (note) run(db, 'INSERT INTO task_logs (request_id, author_id, note, status) VALUES (?, ?, ?, ?)', req.id, user.id, note, next); audit(db, user.id, 'service_request', req.id, `status_changed_to_${next}`); }

function bestTechnician(req) { const needed = req.required_skills; const preferred = req.preferred_skills; const people = many(db, "SELECT id,technician_id,name,site,skills,skill_focus,rating FROM users WHERE role='technician' AND active=1").map(x => ({ ...x, skills: parseJson(x.skills) })); return people.filter(t => t.site === req.site && needed.every(s => t.skills.includes(s)) && (!preferred.length || preferred.some(s => t.skills.includes(s)))).sort((a,b) => { const aLoad=one(db, "SELECT COUNT(*) AS n FROM service_requests WHERE assigned_to=? AND status IN ('assigned','in_progress')", a.id).n; const bLoad=one(db, "SELECT COUNT(*) AS n FROM service_requests WHERE assigned_to=? AND status IN ('assigned','in_progress')", b.id).n; return aLoad-bLoad || (b.rating||0)-(a.rating||0); })[0]; }

async function handler(req, res) {
  if (req.method === 'OPTIONS') return send(res, 204, {});
  const url = new URL(req.url, `http://${req.headers.host}`); const path = url.pathname; const payload = ['POST','PATCH'].includes(req.method) ? await body(req) : {};
  if (req.method === 'GET' && path === '/health') return send(res, 200, { ok:true, time:now() });
  if (req.method === 'POST' && path === '/auth/register') { const {name,email,password,role='requester',site=null,skills=[]}=payload; if (!name || !email || !password) throw Object.assign(new Error('name, email and password are required'), {status:400}); if (!['requester','technician'].includes(role)) throw Object.assign(new Error('Public registration permits requester or technician only'),{status:403}); const r=run(db,'INSERT INTO users (name,email,password_hash,role,site,skills) VALUES (?,?,?,?,?,?)',name,email.toLowerCase(),hashPassword(password),role,site,JSON.stringify(skills)); const user=one(db,'SELECT id,name,email,role,site FROM users WHERE id=?',r.lastInsertRowid); audit(db,user.id,'user',user.id,'registered'); return send(res,201,{user,token:issueToken(user)}); }
  if (req.method === 'POST' && path === '/auth/login') { const user=one(db,'SELECT * FROM users WHERE email=?',String(payload.email||'').toLowerCase()); if (!user || !verifyPassword(payload.password||'',user.password_hash)) throw Object.assign(new Error('Invalid email or password'),{status:401}); return send(res,200,{token:issueToken(user),user:{id:user.id,name:user.name,email:user.email,role:user.role,site:user.site}}); }
  const user = requireUser(req);
  if (req.method === 'GET' && path === '/me') return send(res,200,user);
  if (req.method === 'GET' && path === '/notifications') return send(res,200,many(db,'SELECT * FROM notifications WHERE user_id=? ORDER BY created_at DESC',user.id));
  if (req.method === 'POST' && path === '/users') { allowed(user,roles('admin')); const {name,email,password,role,site=null,skills=[]}=payload; if (!name||!email||!password||!role) throw Object.assign(new Error('name, email, password and role are required'),{status:400}); const r=run(db,'INSERT INTO users (name,email,password_hash,role,site,skills) VALUES (?,?,?,?,?,?)',name,email.toLowerCase(),hashPassword(password),role,site,JSON.stringify(skills)); audit(db,user.id,'user',Number(r.lastInsertRowid),'created'); return send(res,201,one(db,'SELECT id,name,email,role,site,skills FROM users WHERE id=?',r.lastInsertRowid)); }
  if (req.method === 'GET' && path === '/technicians') { allowed(user,roles('admin','dispatcher')); return send(res,200,many(db,"SELECT id,technician_id,name,email,site,skills,skill_focus,rating FROM users WHERE role='technician' AND active=1 ORDER BY rating DESC")); }
  if (req.method === 'GET' && path === '/machines') return send(res,200,many(db,'SELECT * FROM machines ORDER BY site,code'));
  if (req.method === 'POST' && path === '/machines') { allowed(user,roles('admin','dispatcher')); const {code,name,site,required_skills=[]}=payload; if(!code||!name||!site) throw Object.assign(new Error('code, name and site are required'),{status:400}); const r=run(db,'INSERT INTO machines (code,name,site,required_skills) VALUES (?,?,?,?)',code,name,site,JSON.stringify(required_skills)); audit(db,user.id,'machine',Number(r.lastInsertRowid),'created'); return send(res,201,one(db,'SELECT * FROM machines WHERE id=?',r.lastInsertRowid)); }
  if (req.method === 'GET' && path === '/parts') { allowed(user,roles('admin','dispatcher','technician')); return send(res,200,many(db,'SELECT * FROM parts ORDER BY name')); }
  if (req.method === 'POST' && path === '/parts') { allowed(user,roles('admin','dispatcher')); const {sku,name,quantity=0,reorder_level=0}=payload; if(!sku||!name||!Number.isInteger(quantity)||quantity<0) throw Object.assign(new Error('sku, name and non-negative integer quantity are required'),{status:400}); const r=run(db,'INSERT INTO parts (sku,name,quantity,reorder_level) VALUES (?,?,?,?)',sku,name,quantity,reorder_level); audit(db,user.id,'part',Number(r.lastInsertRowid),'created'); return send(res,201,one(db,'SELECT * FROM parts WHERE id=?',r.lastInsertRowid)); }
  if (req.method === 'GET' && path === '/requests') { const clauses=[]; const params=[]; if(user.role==='requester'){clauses.push('r.requester_id=?');params.push(user.id)} if(user.role==='technician'){clauses.push('r.assigned_to=?');params.push(user.id)} if(url.searchParams.get('status')){clauses.push('r.status=?');params.push(url.searchParams.get('status'))} const rows=many(db,`SELECT r.*,m.code machine_code,m.name machine_name,m.site,u.name requester_name,t.name technician_name FROM service_requests r JOIN machines m ON m.id=r.machine_id JOIN users u ON u.id=r.requester_id LEFT JOIN users t ON t.id=r.assigned_to ${clauses.length?'WHERE '+clauses.join(' AND '):''} ORDER BY CASE r.priority WHEN 'urgent' THEN 1 WHEN 'high' THEN 2 WHEN 'medium' THEN 3 ELSE 4 END,r.created_at DESC`,...params).map(requestRow); return send(res,200,rows); }
  if (req.method === 'POST' && path === '/requests') { const {machine_id,title,description='',issue_type=null,priority='medium',required_skills=[],required_parts=[],due_at=null}=payload; const machine=one(db,'SELECT * FROM machines WHERE id=?',machine_id); const issue=issue_type && ISSUE_TYPES[issue_type]; if(!machine||machine.status!=='active') throw Object.assign(new Error('Machine must exist and be active'),{status:400}); if(issue_type&&!issue) throw Object.assign(new Error(`issue_type must be one of: ${Object.keys(ISSUE_TYPES).join(', ')}`),{status:400}); if(!title||!['low','medium','high','urgent'].includes(priority)||!Array.isArray(required_parts)||!Array.isArray(required_skills)) throw Object.assign(new Error('Invalid request fields'),{status:400}); const baseSkills=issue ? [...new Set([...COMMON_SKILLS,...required_skills])] : required_skills; const preferredSkills=issue ? issue.preferredSkills : []; for(const item of required_parts){const part=one(db,'SELECT * FROM parts WHERE id=?',item.part_id);if(!part||!Number.isInteger(item.quantity)||item.quantity<1) throw Object.assign(new Error('Each required part needs a valid part_id and quantity'),{status:400});} const r=run(db,'INSERT INTO service_requests (machine_id,requester_id,title,description,issue_type,priority,required_skills,preferred_skills,required_parts,due_at) VALUES (?,?,?,?,?,?,?,?,?,?)',machine_id,user.id,title,description,issue_type,priority,JSON.stringify(baseSkills),JSON.stringify(preferredSkills),JSON.stringify(required_parts),due_at); audit(db,user.id,'service_request',Number(r.lastInsertRowid),'created',{issue_type}); return send(res,201,getRequest(r.lastInsertRowid)); }
  const match=path.match(/^\/requests\/(\d+)(?:\/(approve|start|complete|reassign|exception|logs|attachments))?$/); if(match){const id=Number(match[1]),action=match[2];const sr=getRequest(id);if(!sr) throw Object.assign(new Error('Service request not found'),{status:404}); if(!action && req.method==='GET'){ if(user.role==='requester'&&sr.requester_id!==user.id||user.role==='technician'&&sr.assigned_to!==user.id) throw Object.assign(new Error('Insufficient permission'),{status:403}); return send(res,200,{...sr,logs:many(db,'SELECT l.*,u.name author_name FROM task_logs l JOIN users u ON u.id=l.author_id WHERE request_id=? ORDER BY created_at',id),attachments:many(db,'SELECT * FROM attachments WHERE request_id=?',id),audit:many(db,'SELECT * FROM audit_events WHERE entity_type=? AND entity_id=? ORDER BY created_at','service_request',id)}); }
    if(req.method==='POST'&&action==='approve'){allowed(user,roles('admin','dispatcher'));if(sr.status!=='pending_approval')throw Object.assign(new Error('Only pending requests can be approved'),{status:409});for(const item of sr.required_parts){const p=one(db,'SELECT * FROM parts WHERE id=?',item.part_id);if(!p||p.quantity<item.quantity)throw Object.assign(new Error(`Insufficient part inventory for part ${item.part_id}`),{status:409});}transition(user,sr,'approved','Request approved');for(const item of sr.required_parts){run(db,'UPDATE parts SET quantity=quantity-? WHERE id=?',item.quantity,item.part_id);run(db,'INSERT INTO part_reservations (request_id,part_id,quantity) VALUES (?,?,?)',id,item.part_id,item.quantity)} const tech=payload.technician_id?one(db,"SELECT * FROM users WHERE id=? AND role='technician' AND active=1",payload.technician_id):bestTechnician(sr);if(tech){run(db,'UPDATE service_requests SET assigned_to=?,updated_at=? WHERE id=?',tech.id,now(),id);transition(user,{...sr,status:'approved'},'assigned',`Assigned to ${tech.name}`);notify(db,tech.id,`You were assigned request #${id}: ${sr.title}`)}else{transition(user,{...sr,status:'approved'},'exception','No qualified technician available');}return send(res,200,getRequest(id));}
    if(req.method==='POST'&&action==='start'){if(user.role!=='technician'||sr.assigned_to!==user.id)throw Object.assign(new Error('Only the assigned technician can start work'),{status:403});transition(user,sr,'in_progress',payload.note||'Work started');return send(res,200,getRequest(id));}
    if(req.method==='POST'&&action==='complete'){if(user.role!=='technician'||sr.assigned_to!==user.id)throw Object.assign(new Error('Only the assigned technician can complete work'),{status:403});if(!payload.verification_note)throw Object.assign(new Error('verification_note is required'),{status:400});transition(user,sr,'completed',payload.verification_note);notify(db,sr.requester_id,`Request #${id} has been completed`);return send(res,200,getRequest(id));}
    if(req.method==='POST'&&action==='reassign'){allowed(user,roles('admin','dispatcher'));if(!['assigned','in_progress','exception'].includes(sr.status))throw Object.assign(new Error('Request cannot be reassigned in its current state'),{status:409});const tech=one(db,"SELECT * FROM users WHERE id=? AND role='technician' AND active=1",payload.technician_id);if(!tech)throw Object.assign(new Error('Active technician not found'),{status:404});run(db,"UPDATE service_requests SET assigned_to=?,status='assigned',updated_at=? WHERE id=?",tech.id,now(),id);run(db,'INSERT INTO task_logs (request_id,author_id,note,status) VALUES (?,?,?,?)',id,user.id,payload.reason||`Reassigned to ${tech.name}`,'assigned');audit(db,user.id,'service_request',id,'reassigned',{technician_id:tech.id});notify(db,tech.id,`You were assigned request #${id}: ${sr.title}`);return send(res,200,getRequest(id));}
    if(req.method==='POST'&&action==='exception'){allowed(user,roles('admin','dispatcher','technician'));if(user.role==='technician'&&sr.assigned_to!==user.id)throw Object.assign(new Error('Only the assigned technician can report an exception'),{status:403});transition(user,sr,'exception',payload.note||'Operational exception reported');notify(db,sr.requester_id,`Request #${id} needs attention`);return send(res,200,getRequest(id));}
    if(req.method==='POST'&&action==='logs'){if(user.role==='requester'&&sr.requester_id!==user.id||user.role==='technician'&&sr.assigned_to!==user.id)throw Object.assign(new Error('Insufficient permission'),{status:403});if(!payload.note)throw Object.assign(new Error('note is required'),{status:400});const r=run(db,'INSERT INTO task_logs (request_id,author_id,note,status) VALUES (?,?,?,?)',id,user.id,payload.note,sr.status);audit(db,user.id,'service_request',id,'log_added');return send(res,201,one(db,'SELECT * FROM task_logs WHERE id=?',r.lastInsertRowid));}
    if(req.method==='POST'&&action==='attachments'){if(user.role==='requester'&&sr.requester_id!==user.id||user.role==='technician'&&sr.assigned_to!==user.id)throw Object.assign(new Error('Insufficient permission'),{status:403});if(!payload.url)throw Object.assign(new Error('url is required'),{status:400});const r=run(db,'INSERT INTO attachments (request_id,author_id,url,kind) VALUES (?,?,?,?)',id,user.id,payload.url,payload.kind||'document');audit(db,user.id,'service_request',id,'attachment_added');return send(res,201,one(db,'SELECT * FROM attachments WHERE id=?',r.lastInsertRowid));}
  }
  if(req.method==='GET'&&path==='/dashboard'){allowed(user,roles('admin','dispatcher'));const byStatus=many(db,'SELECT status,COUNT(*) count FROM service_requests GROUP BY status');const urgent=many(db,"SELECT id,title,priority,status,due_at FROM service_requests WHERE priority IN ('urgent','high') AND status NOT IN ('completed','cancelled') ORDER BY created_at DESC");const lowStock=many(db,'SELECT * FROM parts WHERE quantity<=reorder_level ORDER BY quantity');const overdue=many(db,"SELECT id,title,due_at,status FROM service_requests WHERE due_at<? AND status NOT IN ('completed','cancelled')",now());return send(res,200,{byStatus,urgent,lowStock,overdue});}
  throw Object.assign(new Error('Route not found'),{status:404});
}

http.createServer((req,res)=>handler(req,res).catch(error=>send(res,error.status||500,{error:error.message||'Internal server error'}))).listen(PORT,()=>console.log(`Service API running at http://localhost:${PORT}`));
