-- Run this once in Supabase Dashboard -> SQL Editor. It creates a separate
-- durable Duramint application schema and does not modify the existing
-- technician dataset tables.

create table if not exists public.duramint_users (
  id bigint generated by default as identity primary key,
  technician_id text unique,
  name text not null,
  email text not null unique,
  password_hash text not null,
  role text not null check (role in ('admin', 'dispatcher', 'technician', 'requester')),
  site text,
  skills jsonb not null default '[]'::jsonb,
  skill_focus text,
  rating numeric,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.duramint_machines (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  site text not null,
  status text not null default 'active',
  required_skills jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.duramint_parts (
  id bigint generated by default as identity primary key,
  sku text not null unique,
  name text not null,
  quantity integer not null default 0 check (quantity >= 0),
  reorder_level integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.duramint_service_requests (
  id bigint generated by default as identity primary key,
  machine_id bigint not null references public.duramint_machines(id),
  requester_id bigint not null references public.duramint_users(id),
  title text not null,
  description text,
  issue_type text,
  priority text not null check (priority in ('low', 'medium', 'high', 'urgent')),
  required_skills jsonb not null default '[]'::jsonb,
  preferred_skills jsonb not null default '[]'::jsonb,
  required_parts jsonb not null default '[]'::jsonb,
  status text not null default 'pending_approval' check (status in ('pending_approval', 'approved', 'assigned', 'in_progress', 'completed', 'cancelled', 'exception')),
  assigned_to bigint references public.duramint_users(id),
  due_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.duramint_part_reservations (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.duramint_service_requests(id) on delete cascade,
  part_id bigint not null references public.duramint_parts(id),
  quantity integer not null check (quantity > 0),
  unique (request_id, part_id)
);

create table if not exists public.duramint_task_logs (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.duramint_service_requests(id) on delete cascade,
  author_id bigint not null references public.duramint_users(id),
  note text not null,
  status text,
  created_at timestamptz not null default now()
);

create table if not exists public.duramint_attachments (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.duramint_service_requests(id) on delete cascade,
  author_id bigint not null references public.duramint_users(id),
  url text not null,
  kind text not null default 'document',
  created_at timestamptz not null default now()
);

create table if not exists public.duramint_notifications (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.duramint_users(id) on delete cascade,
  message text not null,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.duramint_audit_events (
  id bigint generated by default as identity primary key,
  actor_id bigint references public.duramint_users(id),
  entity_type text not null,
  entity_id bigint not null,
  action text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists duramint_requests_status_idx on public.duramint_service_requests(status);
create index if not exists duramint_requests_assignee_idx on public.duramint_service_requests(assigned_to);
create index if not exists duramint_users_role_idx on public.duramint_users(role);

alter table public.duramint_users enable row level security;
alter table public.duramint_machines enable row level security;
alter table public.duramint_parts enable row level security;
alter table public.duramint_service_requests enable row level security;
alter table public.duramint_part_reservations enable row level security;
alter table public.duramint_task_logs enable row level security;
alter table public.duramint_attachments enable row level security;
alter table public.duramint_notifications enable row level security;
alter table public.duramint_audit_events enable row level security;

-- No public policies are created. The deployed backend uses the Supabase
-- service-role key, which bypasses RLS; browsers never receive that key.
